name: CI
on: [push, pull_request]
jobs:
  CI-Build:
    name: Langevin on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17.0.7'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: build and test native solver  # https://graalvm.github.io/native-build-tools/latest/maven-plugin.html
        run: mvn -Pnative -DskipTests package

      - name: Upload ${{ matrix.os }} solver binary
        uses: actions/upload-artifact@v4
        with:
          name: langevin-${{ matrix.os }}
          path: target/langevin*
